Sem o uso de numpy, como podemos declarar uma matriz? E como podemos acessar qualquer valor desta? 

In [3]:
import numpy as np

matriz = [[1,2,3],[2,3,4],[3,4,5]]

print(matriz)

[[1, 2, 3], [2, 3, 4], [3, 4, 5]]


Com o uso de numpy, é muito mais simples

In [4]:
np_matriz = np.array(matriz)

np_matriz

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [8]:
#LER ELEMENTO DA MATRIZ
#1ª FORMA
np_matriz[1][1]


3

In [ ]:
#2ªFORMA
np_matriz[1,1]

### Criação de matrizes e vetores

Podemos criar matrizes e vetores de diferentes formas.

- Constante (zeros, ones, etc).

- Com ordenação.

- Aleatória.

#### Constante 

Temos diferentes métodos:

- Zeros (preenche apenas com 0's)

- Ones (preenche apenas com 1's)

- Full (preenche apenas com o valor estipulado)

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Ordenado

Temos alguns exemplos:

- `np.repeat`

- `np.arange`

- `np.linspace`

### Aleatório

Podemos usar de um jeito semelhante ao que fazemos geralmente com a ferramenta random. 

- `np.random.rand`

- `np.random.randint` 

- `np.random.choice`

In [47]:
matriz_aleatoria = np.random.rand(3,3)

matriz_aleatoria.sort()

print(matriz_aleatoria)



[[0.12706699 0.58349718 0.81945098]
 [0.2189166  0.64486949 0.87078313]
 [0.01053582 0.02381033 0.18032918]]


In [34]:
matriz_inte = np.random.randint(0, high=5, size=(3,7))

matriz_inte

array([[3, 1, 1, 4, 3, 0, 0],
       [3, 4, 2, 0, 3, 3, 4],
       [3, 4, 2, 2, 0, 1, 2]])

### Shapes, reshapes e resizes

Na prática, precisamos mudar frequentemente o formato dos dados apresentados em um `np.ndarray`, tanto em seus valores como também em suas dimensões. 

Considere, por exemplo, um problema que armazenamos uma informação de mercado em três dimensões, onde a primeira dimensão contém os valores em cada um dos dias, a segunda dimensão contém os produtos e a terceira dimensão está relacionado com o departamento do mercado. 

Queremos transformar este **tensor** para que tenha apenas duas dimensões, sendo a primeira contendo os valores em cada um dos dias, e a segunda dimensão contendo todos os produtos, independentemente do departamento. Como faremos isso? 

In [15]:
vetor=[1,2,3,4,5,6,7,8,9]

np_vetor = np.array(vetor)
print(np_vetor)

[1 2 3 4 5 6 7 8 9]


In [16]:
np_vetor.shape

(9,)

In [18]:
#obedecer a quantidade de elementos se dar para formar a matriz
np_vetor.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#Para ãlo observar a quantidade de linhas, e colocar -1 no primeiro argumento
vetor1=[1,2,3,4,5,6,7,8,9, 10, 11, 12]
np_vetor1 = np.array(vetor1)
print(np_vetor1)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
np_vetor1.shape

np_vetor1.reshape((-1,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Exercícios de fixação

1. Escreva um programa para criar um array Numpy com 10 números aleatórios e ordená-los de forma crescente.

2. Escreva um programa para realizar soma e subtração elemento a elemento entre dois arrays Numpy com o mesmo tamanho.

3. Escreva um programa para calcular o produto escalar entre dois arrays Numpy.

4. Escreva um programa para criar um array Numpy com os valores de 0 a 9 e mudar a forma para uma matriz 3x3.

5. Escreva um programa para extrair todos os números pares de um array Numpy e armazená-los em um novo array Numpy.

6. Escreva um programa para criar um array Numpy com os valores de 1 a 10 e calcular a soma acumulada dos elementos.

7. Escreva um programa para calcular a média e o desvio padrão de um array Numpy ao longo de um eixo específico.

8. Escreva um programo para criar um array Numpy com os valores de 1 a 5 e repetir os valores 3 vezes ao longo do primeiro eixo.

9. Escreva um programa para realizar comparações elemento a elemento entre dois arrays Numpy e retornar um array Numpy Booleano com os resultados.

10. Escreva um programa para criar um array Numpy com os valores de 1 a 10 e substituir todos os números ímpares por -1.

In [65]:
#1. Escreva um programa para criar um array Numpy com 10 números aleatórios e ordená-los de forma crescente.
matriz10 = np.random.randint(1,10,10,)
matriz10.sort()
print(matriz10)

[1 3 4 5 5 5 7 8 8 9]


In [6]:
import numpy as np

#Bucas de forma aleatoria os números da MEGA SENA
matrizme = np.arange(1,25)
Num_sorteado = np.random.choice(matrizme,size=15, replace=False)
Num_sorteado1 = list(Num_sorteado)

print(sorted(Num_sorteado1))


[1, 3, 5, 6, 8, 9, 12, 14, 15, 16, 18, 20, 21, 22, 23]


In [64]:
#2. Escreva um programa para realizar soma e subtração elemento a elemento entre dois arrays Numpy com o mesmo tamanho.
matriz10 = np.random.randint(1,10,5,)
matriz20 = np.random.randint(1,10,5)
print(matriz10)
print(matriz20)
matrizf = np.add(matriz10, matriz20)
print(matrizf)

[4 5 4 2 1]
[7 5 7 4 5]
[11 10 11  6  6]


In [68]:
#3. Escreva um programa para calcular o produto escalar entre dois arrays Numpy.
matriz10 = np.random.randint(1,10,5,)
matriz20 = np.random.randint(1,10,5)
print(matriz10)
print(matriz20)
matrizf = np.dot(matriz10, matriz20)
print(matrizf)

[9 1 4 4 3]
[9 3 6 7 2]
142


In [72]:
#4. Escreva um programa para criar um array Numpy com os valores de 0 a 9 e mudar a forma para uma matriz 3x3.
matriz4 = np.arange(0,9)
print(matriz4)
matriz4f = matriz4.reshape((3,3))
print(matriz4f)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [127]:
matriz4_1 = np.arange(1,6).reshape((1,5))

np.concatenate((matriz4_1, matriz4_1, matriz4_1),axis=0)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [78]:
#5. Escreva um programa para extrair todos os números pares de um array Numpy e armazená-los em um novo array Numpy.
matriz4 = np.arange(0,9)
print(matriz4)
Matriz4par = matriz4[matriz4 % 2 == 0]
print(Matriz4par)


[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]


In [77]:
array_01_ex05 = np.arange(0,10)
print(array_01_ex05)

array_02_ex05 = []
for valor in array_01_ex05:
    if valor % 2 == 0:
        array_02_ex05.append(valor)

print(array_02_ex05)

[0 1 2 3 4 5 6 7 8 9]
[0, 2, 4, 6, 8]


In [79]:
# 6. Escreva um programa para criar um array Numpy com os valores de 1 a 10 e calcular a soma acumulada dos elementos.
matriz5 = np.arange(1,10)
print(matriz5)
matriz5f = sum(matriz5)

print(matriz5f)

[1 2 3 4 5 6 7 8 9]
45


In [118]:
# 7. Escreva um programa para calcular a média e o desvio padrão de um array Numpy ao longo de um eixo específico.
matriz6 = np.arange(2,10)
print(matriz6)
matriz6f = np.average(matriz6)
print(matriz6f)



[2 3 4 5 6 7 8 9]
5.5


In [125]:
#se for mais de uma linha podemos utilizar o oaxi
arr = np.random.rand(2,2)
print(arr)
axis_ = 1
arrm = np.mean(arr, axis=axis_)
print(arrm)

[[0.4022342  0.853023  ]
 [0.83006197 0.67850324]]
[0.6276286 0.7542826]


In [86]:
def exercicio_7(array=np.arange(1,10)) -> tuple:
    """Escreva um programa para calcular a média e o desvio padrão de um array Numpy ao longo de um eixo específico."""
    return (array.mean(), array.std())
exercicio_7()

(5.0, 2.581988897471611)

In [87]:
# 8. Escreva um programo para criar um array Numpy com os valores de 1 a 5 e repetir os valores 3 vezes ao longo do primeiro eixo.
matriz8 = np.arange(1,6)
print(matriz8)
matriz8f = np.repeat(matriz8, 3)
print(matriz8f)

[1 2 3 4 5]
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [95]:
# 9. Escreva um programa para realizar comparações elemento a elemento entre dois arrays Numpy e retornar um array Numpy Booleano com os resultados.
matriz9 = np.array([1,2,3,4,5])
matriz9_2 = np.array([1,3,4,6,5])
print(matriz9)
print(matriz9_2)
matriz9f = matriz9 == matriz9_2

print(matriz9f)

[1 2 3 4 5]
[1 3 4 6 5]
[ True False False False  True]


In [96]:
matriz9 = [1,2,3,4,5]
matriz9_2 = [1,3,4,6,5]
matriz9p = np.array(matriz9)
matriz9_2p = np.array(matriz9_2)
print(matriz9)
print(matriz9_2)
matriz9f = matriz9p == matriz9_2p

print(matriz9f)

[1, 2, 3, 4, 5]
[1, 3, 4, 6, 5]
[ True False False False  True]


In [103]:
# 10. Escreva um programa para criar um array Numpy com os valores de 1 a 10 e substituir todos os números ímpares por -1.
matriz10 = np.arange(1,11)
print(matriz10)
matriz10[matriz10 % 2 != 0]=-1

print(matriz10)


[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [132]:
arr = np.arange(1,11)
arr_impar = np.copy(arr)

arr_impar[arr_impar %2 != 0] = -1

print(arr_impar)
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
array_01_ex10 = np.arange(0,10)
print(array_01_ex10)

array_02_ex10f = []
for valor in array_01_ex10:
    if valor % 2 != 0:
        array_02_ex10f.append(-1)
    elif valor % 2 ==0:
        array_02_ex10f.append(valor)

print(array_02_ex10f)

## Exercício

1. Considere que você esteja trabalhando em uma equipe de metereologia e queira fazer uma análise de chuvas em diferentes regiões de um estado do Brasil. Cada região é representada por 4 bairros, com informações armazenadas de precipicação diária, totalizando 8 regiões.

Um analista da empresa carregou todas as bases de precipitação (primeiro eixo contendo as precipitações diárias em um mês e o segundo eixo os bairros), concatenando estas informações em um novo eixo (i.e. terceiro eixo contém as regiões). 

a) Gere uma função que calcule a precipitação média diária para cada uma das 8 regiões.
b) Gere uma função que também calcule a precipitação média diária no estado.
c) Gere uma função que diga o bairro e a região que contém a maior precipitação mensal (ou seja, indique apenas o índice do bairro e o índice da região).

2. Você recebeu informações de todos os clientes de uma academia. Com o objetivo de verificar a saúde e obter novas informações sobre essas pessoas, você foi encarregado de criar um sistema que extraia algumas informações para a orientação de novas atividades da academia. Para isso, crie um sistema que extraia as seguintes informações:

- O cálculo do Índice de Massa Corpórea (IMC) de cada pessoa.
- A quantidade e proporção de clientes em cada grupo, de acordo com o IMC.
- A quantidade de pessoas acima de 90 kg **e** abaixo de 1.70 m.

In [1]:
import numpy as np

In [4]:
lista_imc = [[1.788810693, 65.64810194, 0],
[1.566784434, 76.64276798, 0],
[2.092193055, 55.46818533, 1],
[1.782470917, 67.28199736, 1],
[1.735766977, 69.28900763, 0],
[1.686974648, 56.84005114, 0],
[1.797104633, 65.20897328, 1],
[1.187349055, 48.16476395, 0],
[1.595891436, 45.41064814, 1],
[1.396281776, 67.93011334, 0],
[1.606148165, 67.71960410, 0],
[1.707589967, 45.60933262, 0],
[1.735513116, 64.84545151, 0],
[1.672055182, 39.70595150, 1],
[1.723377069, 50.05888021, 1],
[1.684574272, 56.54508738, 1],
[1.733258930, 37.51218759, 0],
[1.757899659, 57.36242239, 0],
[1.913337705, 69.30724639, 1],
[1.456048343, 69.34233711, 0]]

In [45]:
mdados = np.array(lista_imc)

altura = mdados[0][0]
peso = mdados[0,1]

mdados = mdados[:,1]/mdados[:,0]**2

print(mdados)


[20.51603397 31.22142238 12.67186232 21.17648966 22.9975461  19.97272618
 20.19113045 34.16430689 17.82998641 34.84305286 26.25083963 15.6417928
 21.52899308 14.20215982 16.85467996 19.92574428 12.48663735 18.56262193
 18.93195156 32.70746506]


In [47]:
def imc_calculo(dados):

    imc = dados[:,1]/dados[:,0]**2

    return imc

matriz_dados = np.array(lista_imc)
imc_calculo(matriz_dados)

array([20.51603397, 31.22142238, 12.67186232, 21.17648966, 22.9975461 ,
       19.97272618, 20.19113045, 34.16430689, 17.82998641, 34.84305286,
       26.25083963, 15.6417928 , 21.52899308, 14.20215982, 16.85467996,
       19.92574428, 12.48663735, 18.56262193, 18.93195156, 32.70746506])

3. Hoje em dia, o IMC é visto como um método "ultrapassado", surgindo novas alternativas como o Índice de Adiposidade Corporal (IAC), que usa a medida da cintura para o cálculo. Crie uma nova função que calcule o IAC e extraia as estatísticas semelhantes ao que foi anunciado para o IMC. Em seguida, crie uma nova função (que utiliza as duas já criadas anteriormente) para verificar se existe uma certa correspondência entre os dois métodos.

## Desafios

1. Sudoku é um jogo de lógica muito popular. Segundo [fonte](https://pt.wikipedia.org/wiki/Sudoku), o objetivo do jogo é a colocação de números de 1 a 9 em cada uma das células vazias numa grade de 9x9, constituída por 3x3 subgrades chamadas regiões. Um jogo é válido apenas se tiver um número distinto (de 1 a 9) em cada linha, coluna ou região. 

Crie uma função que verifique se o jogo é válido ou não. Para isso, a função deve receber como argumento de entrada uma matriz 9 x 9 e obrigatoriamente retornar um `bool`, onde `True` significa que o jogo é válido e `False` como inválido. 

**Extra**: Caso a função retorne `False`, retorne também uma matriz de posições indicando quais células invalidaram o jogo.

2. A área de processamento de imagens demanda um grande conhecimento sobre matrizes e cálculos matriciais. Por exemplo, podemos pensar em uma imagem como uma grande matriz de pixels, onde cada valor desta matriz representa a intensidade de cor. 
Geralmente as imagens estão presentes no espaço de cores **RGB**, e as informações armazenadas são, na verdade, contidas em um tensor com três dimensões (H x W x C). 

Em processamento de imagens, podemos fazer uso desse conhecimento para transformação de imagens (ou edição). Para isso, faça o que se pede a seguir:

- Crie uma função que converta uma imagem RGB em escala de cinza. Procure na Internet a formulação matemática e realize tal procedimento. 

- Pesquise sobre transformações de imagem (e.g. gamma correction) e implemente uma destas funções.

